
services:
  mamas-kitchen:
    build:
      context: .
      dockerfile: Dockerfile.mamas-kitchen
    container_name: mamas-kitchen
    depends_on:
      - azureite
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azureite:10000/devstoreaccount1;QueueEndpoint=http://azureite:10001/devstoreaccount1;TableEndpoint=http://azureite:10002/devstoreaccount1;
    ports:
      - "8000:8000"

  azureite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azureite
    ports:
      - "10000:10000"
      - "10001:10001"
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0"
  
  open-ai:
    image: localai/localai:v2.25.0-ffmpeg-core
    # For a specific version:
    # image: localai/localai:v2.25.0-aio-cpu
    # For Nvidia GPUs decomment one of the following (cuda11 or cuda12):
    # image: localai/localai:v2.25.0-aio-gpu-nvidia-cuda-11
    # image: localai/localai:v2.25.0-aio-gpu-nvidia-cuda-12
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-11
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      # ...
    volumes:
      - ./models:/build/models:cached
